---
- name: Derek Vagrant Base Provisioning
  hosts: all
  become: true
  ignore_errors: True

  tasks:
    - name: include per-distro tasks
      include_tasks: "includes/{{ ansible_os_family }}.yml"

    - name: install packages
      package:
        name: "{{ item }}"
        state: installed
      with_items: "{{ derek_vagrant_packages[ansible_os_family] }}"

    - name: template out history file
      template:
        src:
          templates/history.sh.j2
        dest: /etc/profile.d/history.sh
        owner: root
        group: root
        mode: 0644
