---
- name: Derek Vagrant Base Provisioning
  hosts: all
  become: true
  ignore_errors: True

  tasks:
    - name: debug 
      debug:
        var: use_local_yum_mirrors

    - name: include per-distro tasks
      include_tasks: "includes/{{ ansible_distribution }}.yml"

    - name: install packages
      package:
        name: "{{ item }}"
        state: "{{ derek_vagrant_packages_state[ansible_os_family] }}"
      with_items: "{{ derek_vagrant_packages[ansible_os_family] }}"

    - name: template out history file
      template:
        src:
          templates/history.sh.j2
        dest: /etc/profile.d/history.sh
        owner: root
        group: root
        mode: 0644

    - name: debug ansible_default_ipv4
      debug:
        var: ansible_default_ipv4


